version: "3.8"

services:
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - book-service
      - transaction-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8080
      - BOOK_SERVICE_URL=http://book-service:8081
      - TRANSACTION_SERVICE_URL=http://transaction-service:8083
    env_file:
      - ./gateway-service/.env

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    depends_on:
      - email-service
    environment:
      - EMAIL_SERVICE_URL=http://email-service:8084
    env_file:
      - ./auth-service/.env

  book-service:
    build:
      context: ./book-service
    container_name: book-service
    ports:
      - "8082:8081"
    env_file:
      - ./book-service/.env

  email-service:
    build:
      context: ./email-service
    container_name: email-service
    ports:
      - "8084:8084"
    env_file:
      - ./email-service/.env

  transaction-service:
    build:
      context: ./transaction-service
    container_name: transaction-service
    ports:
      - "8083:8083"
    env_file:
      - ./transaction-service/.env
